<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulir Pendaftaran</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        form {
            max-width: 500px;
            margin: auto;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        input, textarea, button {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button {
            background-color: #4CAF50;
            color: white;
            cursor: pointer;
        }
        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <h1>Formulir Pendaftaran</h1>
    <form id="registrationForm">
        <label for="name">Nama Lengkap</label>
        <input type="text" id="name" name="name" required>

        <label for="email">Email</label>
        <input type="email" id="email" name="email" required>

        <label for="phone">Nomor Telepon</label>
        <input type="text" id="phone" name="phone" required>

        <label>Jenis Kelamin</label>
        <label><input type="radio" name="gender" value="Pria" required> Pria</label>
        <label><input type="radio" name="gender" value="Wanita" required> Wanita</label>

        <label for="address">Alamat</label>
        <textarea id="address" name="address" rows="4" required></textarea>

        <label for="birthdate">Tanggal Lahir</label>
        <input type="date" id="birthdate" name="birthdate" required>

        <button type="submit">Kirim</button>
    </form>
    <script>
        document.getElementById('registrationForm').addEventListener('submit', function(event) {
            event.preventDefault();
            alert('Formulir telah dikirim!');
        });
    </script>
</body>
</html>

